### ISSUE TITLE
Pipeline test failure with correct local execution

### ISSUE THREAD

**Issue by ironfede** [ironfede/openmcdf#170]
@jeremy-visionaid we have a big issue on test side as you cane see from pipeline failures...
I cannot replicate in the local environment. 
Maybe there is some issue with dispose - pattern used for CompoundFile?

I think it's been introduced or been unhided in #167 

Could you please have a look? Many thanks @jeremy-visionaid

**Comment by ironfede** [comment]
This is the stack trace:

```
Assert.ThrowsException failed. Threw exception CFFileFormatException, but exception CFException was expected.

Exception Message: Unsupported Binary File Format version: OpenMcdf only supports Compound Files with major version equal to 3 or 4

Stack Trace:    
at OpenMcdf.Header.CheckVersion() in //sources/OpenMcdf/Header.cs:line 151
at OpenMcdf.Header.Read(Stream stream) in //sources/OpenMcdf/Header.cs:line 127
at OpenMcdf.CompoundFile.Load(Stream stream) in //sources/OpenMcdf/CompoundFile.cs:line 611
at OpenMcdf.CompoundFile.LoadFile(String fileName) in //sources/OpenMcdf/CompoundFile.cs:line 661
at OpenMcdf.CompoundFile..ctor(String fileName, CFSUpdateMode updateMode, CFSConfiguration configParameters) 
in //sources/OpenMcdf/CompoundFile.cs:line 329
at OpenMcdf.CompoundFile..ctor(String fileName) in //sources/OpenMcdf/CompoundFile.cs:line 297
at OpenMcdf.Test.CompoundFileTest.<>c__DisplayClass44_0.<Test_FIX_BUG_96_CompoundFile_SaveOverwrite>b__1() in /home/vsts/work/1/s/sources/Test/OpenMcdf.Test/CompoundFileTest.cs:line 1188
at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.ThrowsException[T](Action action, String message, Object[] parameters)
```

**Comment by jeremy-visionaid** [comment]
Yeah, stranglely it works OK on Windows for me. I'd need to Switch over to Ubuntu to repro/debug there perhaps, but maybe we should just do:

```
diff --git a/sources/Test/OpenMcdf.Test/CompoundFileTest.cs b/sources/Test/OpenMcdf.Test/CompoundFileTest.cs
index 3b48cb1..f8d2e27 100644
--- a/sources/Test/OpenMcdf.Test/CompoundFileTest.cs
+++ b/sources/Test/OpenMcdf.Test/CompoundFileTest.cs
@@ -1182,7 +1182,7 @@ namespace OpenMcdf.Test
                 compoundFile.SaveAs(filename2);
             });

-            Assert.ThrowsException<CFException>(() =>
+            Assert.ThrowsException<CFFileFormatException>(() =>
             {
                 string rootedPath = Path.GetFullPath(filename2);
                 using CompoundFile compoundFile = new(rootedPath);

```

**Comment by jeremy-visionaid** [comment]
It's been a while since I booted to Ubuntu for me to test it, but maybe it's worth a punt just merging this
